### ISSUE TITLE
net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.bored.morefuelsmod.Main$ServerProxy

### ISSUE THREAD

**Issue by zygimantus** [boredherobrine13/morefuelsmod-1.10#2]
This error is caused when launching the mod in server, crash-report is here:

```

> ---- Minecraft Crash Report ----
> // I'm sorry, Dave.
> 
> Time: 16.7.22 19.56
> Description: Exception in server tick loop
> 
> net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.bored.morefuelsmod.Main$ServerProxy
>   at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:88)
>   at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:557)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
>   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
>   at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531)
>   at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
>   at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
>   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassNotFoundException: com.bored.morefuelsmod.Main$ServerProxy
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:72)
>   at java.lang.Class.forName0(Native Method)
>   at java.lang.Class.forName(Class.java:348)
>   at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:71)
>   ... 28 more
> Caused by: java.lang.NullPointerException
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
>   ... 34 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.10.2
>   Operating System: Linux (amd64) version 4.6.4-1-ARCH
>   Java Version: 1.8.0_92, Oracle Corporation
>   Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 193365384 bytes (184 MB) / 313524224 bytes (299 MB) up to 902299648 bytes (860 MB)
>   JVM Flags: 0 total; 
>   IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>   FML: MCP 9.32 Powered by Forge 12.18.1.2014 6 mods loaded, 6 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UC  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
>   UC  FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2014-universal.jar) 
>   UC  Forge{12.18.1.2014} [Minecraft Forge] (forge-1.10.2-12.18.1.2014-universal.jar) 
>   UC  journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
>   UE  morefuelsmod-1.10.2{1.4.0} [�4More Fuels Mod] (morefuelsmod-1.10.2-1.4.0.jar) 
>   UC  harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar) 
>   Loaded coremods (and transformers): 
>   Profiler Position: N/A (disabled)
>   Is Modded: Definitely; Server brand changed to 'fml,forge'
>   Type: Dedicated Server (map_server.txt)
```

**Comment by boredhero** [comment]
So is it missing a class or is there something wrong with my existing class. Kinda confused about .Main$ServerProxy

**Comment by boredhero** [comment]
It appears we need another class called "ServerProxy.java" I assumed commonproxy.java. I tried to implement a class, but after adding it to the main.java file it just crashed more on both sides this time.
